# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James Washington
email: jbwashington@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "30 year-old front end web developer from Little Rock, Arkansas."
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://jameswashington.me # the base hostname & protocol for your site
enforce_ssl: jameswashington.me
twitter_username: jbw014
github_username:  jbwashington

  # Build settings
markdown: kramdown

include:
  -.nojekyll

exclude:
  -node_modules
  -package.json
  -bower_components
  -bower.json
  -Gruntfile.coffee
  -Rakefile
