# SITE SETTINGS
title: James Washington
email: jbwashington@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Official fan page for James Washington.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jameswashington.me" # the base hostname & protocol for your site
twitter_username: jbw014
github_username:  jbwashington
google_analytics: 'UA-62702125-1'

  # URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: "https://avatars0.githubusercontent.com/u/3478078?v=3&s=460"

  # BUILD SETTINGS
exclude: ["gulpfile.js", "bower_components", "node_modules", "bower.json", "package.json"]
