# SITE SETTINGS
title: James Washington
email: jbwashington@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Official fan page for James Washington.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jameswashington.me" # the base hostname & protocol for your site
twitter_username: jbw014
github_username:  jbwashington

# BUILD SETTINGS
exclude: ["bower_components", "node_modules", "bower.json", "package.json"]
